version: 0.2

env:
  variables:
    # Disable terminal colour.
    # https://docs.cypress.io/guides/references/changelog.html#3-0-0
    NO_COLOR: 1
    TERM: 'xterm-mono'

phases:
  install:
    commands:
      - yarn install --frozen-lockfile

  build:
    on-failure: CONTINUE
    commands:
      - yarn cy:run:ci

  post_build:
    commands:
      - aws s3 cp --recursive cypress/screenshots s3://results-xp-cypress-demo/${CODEBUILD_BUILD_ID}
      - aws s3 cp --recursive cypress/videos s3://results-xp-cypress-demo/${CODEBUILD_BUILD_ID}