version: 0.2

env:
  variables:
    # Disable terminal colour.
    # https://docs.cypress.io/guides/references/changelog.html#3-0-0
    NO_COLOR: 1
    TERM: 'xterm-mono'

phases:
  install:
    commands:
      - yarn install --frozen-lockfile

  pre_build:
    commands:
      # https://blog.joshwalsh.me/aws-gatsby/ 
      #
      # - echo "Invalidating CloudFront cache"
      # - | 
      #   aws cloudfront wait invalidation-completed --distribution-id $CLOUDFRONT_DISTRIBUTION \
      #   --id $(aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*" | tr '\n' ' ' | sed -r 's/.*"Id": "([^"]*)".*$/\1/')

  build:
    on-failure: CONTINUE
    commands:
      - yarn cy:run:ci

  post_build:
    commands:
      - aws s3 cp cypress/screenshots s3://results-xp-cypress-demo/$CODEBUILD_BUILD_ID
      - aws s3 cp cypress/videos s3://results-xp-cypress-demo/$CODEBUILD_BUILD_ID